src/main/java/com/elec5619/bitpal/domain/Friends.java
package com.elec5619.bitpal.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name="Friends")
public class Friends implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue
	@Column(name="Id")
	private long id;
	
	@ManyToOne
	@JoinColumn(name="User")
	private User user; 
	
	@ManyToOne
	@JoinColumn(name="UserFriend")
	private User userFriend; 
		
}
	

src/main/java/com/elec5619/bitpal/domain/Item.java
package com.elec5619.bitpal.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="Item")
public class Item 
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	@Column(name="Id")
	private long id;

	@Column(name="Name")
	private String name;
	
	@Column(name="Price")
	private Double price;
	
	@Enumerated(EnumType.STRING)
	@Column(name="Type")
	private Type type;
	
	@Column(name="Equipped")
	private boolean isEquipped;
	

	
	////////////////////////////////////////
	
	public long getId() {
		return id;
	}
	
	public void setId(long ID) {
		this.id=ID;
	}


	public boolean isEquipped() {
		return isEquipped;
	}

	public void setEquipped(boolean isEquipped) {
		this.isEquipped = isEquipped;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
	
	public String getName()
	{
		return name;
	}
	
	public void setPrice(double price)
	{
		this.price = price;
	}
	
	public Double getPrice()
	{
		return price;
	}
	
	public void setType(Type type)
	{
		this.type = type;
	}
	
	public Type getType()
	{
		return type;
	}
}

src/main/java/com/elec5619/bitpal/web/AvatarCustomizationController.java
package com.elec5619.bitpal.web;

import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.taglibs.standard.tag.common.core.RemoveTag;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.Item;
import com.elec5619.bitpal.domain.Type;
import com.elec5619.bitpal.service.ItemsManager;

@Controller
public class AvatarCustomizationController
{
	@Resource(name="itemManager")
	private ItemsManager itemManager;
	
	protected final Log logger = LogFactory.getLog(getClass());

	@RequestMapping(value = "/avatarcustomization", method = RequestMethod.GET)
	public String avatarcustomization(Locale locale, Model model, HttpServletRequest httpServletRequest)
	{
		HttpSession session = httpServletRequest.getSession();
		
		
		if(session.getAttribute("AuthenticatedUser") == null)
		{
			return "login";
		}
		
		
		String now = (new Date()).toString();
		logger.info("Returning view avatar customization at time " + now);
		
//		if (itemManager.getItems().isEmpty())
//		{
//			Item item = new Item();
//			item.setName("Master Sword");
//			item.setPrice(100.0);
//			item.setType(Type.WEAPON);
//			item.setEquipped(true);
//			itemManager.addItem(item);
//			
//			Item item2 = new Item();
//			item2.setName("Link's Hat");
//			item2.setPrice(40.0);
//			item2.setType(Type.HAT);
//			item2.setEquipped(true);
//			itemManager.addItem(item2);
//			
//			Item item3 = new Item();
//			item3.setName("Link's Tunic");
//			item3.setPrice(40.0);
//			item3.setType(Type.SHIRT);
//			item3.setEquipped(true);
//			itemManager.addItem(item3);
//			
//			Item item4 = new Item();
//			item4.setName("Link's Pants");
//			item4.setPrice(40.0);
//			item4.setType(Type.PANTS);
//			item4.setEquipped(true);
//			itemManager.addItem(item4);
//			
//			Item item5 = new Item();
//			item5.setName("Link's Boots");
//			item5.setPrice(40.0);
//			item5.setType(Type.BOOTS);
//			item5.setEquipped(true);
//			itemManager.addItem(item5);
//			
//			item = new Item();
//			item.setName("Goron Gloves");
//			item.setPrice(60.0);
//			item.setType(Type.GLOVES);
//			item.setEquipped(false);
//			itemManager.addItem(item);
//			
//			item = new Item();
//			item.setName("Goron's Tunic");
//			item.setPrice(60.0);
//			item.setType(Type.SHIRT);
//			item.setEquipped(false);
//			itemManager.addItem(item);
//			
//		}
				
		
		//Type type = itemManager.getTypeOfItem(item);
		
		model.addAttribute("now", now);
		//model.addAttribute("type", type);
		model.addAttribute("items",itemManager.getItems());
	
		
		return "avatarcustomization";
	}
	
	/**
	 * User has sent information for registration
	 */
	@RequestMapping(value = "/avatarcustomization", method = RequestMethod.POST)
	public String toggelEquip(HttpServletRequest httpServletRequest)
	{
		String idString = httpServletRequest.getParameter("id");
		String current = httpServletRequest.getParameter("current");
		
		long id = Long.parseLong(idString);
		
		Item item = itemManager.getItemByID(id);
		
		List<Item> equippedItems = itemManager.getEquippedItems();
		
		if (current.equals("Unequip"))
		{
			item.setEquipped(false);
			itemManager.updateItem(item);
		} else {
			for (Item i: equippedItems)
			{
				if (i.getType() == item.getType())
				{
					i.setEquipped(false);
					itemManager.updateItem(i);
				}
			}
			item.setEquipped(true);
			itemManager.updateItem(item);
		}
		
		
		return "redirect:/avatarcustomization";
	}

}

src/main/java/com/elec5619/bitpal/web/BattleController.java
package com.elec5619.bitpal.web;

import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.User;
import com.elec5619.bitpal.service.UserManager;

@Controller
public class BattleController {
	User friendUser;
	long friendScore;
	long userScore;
	@Resource(name="userManager")
	UserManager userManager;
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/battle", method = RequestMethod.GET)
	public String login(Locale locale, Model model, HttpServletRequest httpServletRequest) {
		HttpSession session = httpServletRequest.getSession();
		model.addAttribute("self", session.getAttribute("AuthenticatedUser"));
		model.addAttribute("friend", friendUser);
		model.addAttribute("userScore", userScore);
		model.addAttribute("friendScore", friendScore);

		return "battle";
	}
	
	@RequestMapping(value = "/battle", method = RequestMethod.POST)
		public String battle(HttpServletRequest httpServletRequest) {
		String self = httpServletRequest.getParameter("self");
		String friend = httpServletRequest.getParameter("friend");
		System.out.println("self = " + self);
		System.out.println("friend = " + friend);
		friendUser = userManager.getUserByName(friend);
		User selfUser = userManager.getUserByName(self);
		friendScore = friendUser.getAttack() + friendUser.getDefense() + friendUser.getExperience() + friendUser.getHealth();
		userScore = selfUser.getAttack() + selfUser.getDefense() + selfUser.getExperience() + selfUser.getHealth();
		System.out.println("Friendscore = " + friendScore);
		System.out.println("Userscore = " + userScore);
			
		return "redirect:/battle";
		
	}

}

src/main/java/com/elec5619/bitpal/web/DashboardController.java
package com.elec5619.bitpal.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.User;
import com.elec5619.bitpal.service.UserManager;

@Controller
public class DashboardController 
{
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);

	@Resource(name="userManager")
	private UserManager userManger;
	/**
	 * Show dashboard page
	 */
	@RequestMapping(value ="/dashboard", method = RequestMethod.GET)
	public String dashboard(Locale locale, Model model, HttpServletRequest httpServletRequest)
	{
		return "redirect:/";
	}
	
	
}

src/main/java/com/elec5619/bitpal/web/FriendsController.java
package com.elec5619.bitpal.web;

import java.util.List;

import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.Item;
import com.elec5619.bitpal.domain.User;
import com.elec5619.bitpal.service.ItemsManager;
import com.elec5619.bitpal.service.UserManager;

@Controller
public class FriendsController {
	
	//User self;

	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	@Resource(name="userManager")
	UserManager userManager;
	@RequestMapping(value = "/friends", method = RequestMethod.GET)
	public String login(Locale locale, Model model, HttpServletRequest httpServletRequest) {

		HttpSession session = httpServletRequest.getSession();
		
		
		if(session.getAttribute("AuthenticatedUser") == null)
		{
			return "login";
		}
		
		model.addAttribute("users", userManager.getUsers());
		model.addAttribute("friends", userManager.getFriends());
		
		model.addAttribute("self", session.getAttribute("AuthenticatedUser"));
	
		
		//List <User> user = userManager.getUsers();
		
		return "friends";
	}

	@RequestMapping(value = "/friends", method = RequestMethod.POST)
	public String getFriends(HttpServletRequest httpServletRequest) {
		
		String idString = httpServletRequest.getParameter("id");
		String current = httpServletRequest.getParameter("current");
		//HttpSession session = httpServletRequest.getSession();
		
		long id = Long.parseLong(idString);
		User user = userManager.getUserById(id);
		//self = (User) session.getAttribute("authenticated");
		
		if (current.equals("Add Friend")) {
			user.setFriend(true);
			userManager.updateUser(user);
			
		} else {
			user.setFriend(false);
			userManager.updateUser(user);
		}
		
		//List <User> users = userManager.getUsers();
		//List <User> friends = userManager.getFriends();
		
		//return users; // return page you want to get to
		return "redirect:/friends";
		
	}


}

src/main/java/com/elec5619/bitpal/web/FriendsProfileController.java
package com.elec5619.bitpal.web;

import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.User;
import com.elec5619.bitpal.service.UserManager;

@Controller
public class FriendsProfileController {
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	@Resource(name="userManager")
	UserManager userManager;
	User user;
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/friendsProfile", method = RequestMethod.GET)
	public String login(Locale locale, Model model, HttpServletRequest httpServletRequest) {
		HttpSession session = httpServletRequest.getSession();
		model.addAttribute("self", session.getAttribute("AuthenticatedUser"));
		model.addAttribute("friend", user);
		
		return "friendsProfile";
	}
	
	@RequestMapping(value = "/friendsProfile", method = RequestMethod.POST)
	public String getFriend(HttpServletRequest httpServletRequest) {
		String idString = httpServletRequest.getParameter("id");
		long id = Long.parseLong(idString);
		user = userManager.getUserById(id);
		return "redirect:/friendsProfile";
		
	}

}

src/main/java/com/elec5619/bitpal/web/HomeController.java
package com.elec5619.bitpal.web;

import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.service.UserManager;


/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	@Resource(name="userManager")
	UserManager userManager;
	
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model, HttpServletRequest httpServletRequest) {
		HttpSession session = httpServletRequest.getSession();
		if (session.getAttribute("Authentication") == null)
			return "redirect:login";
		if (session.getAttribute("Authentication").equals("false"))
			return "redirect:login";
		
		model.addAttribute("user", session.getAttribute("AuthenticatedUser"));
		
//		session.setAttribute("Authentication", "false");
//		session.setAttribute("AttemptedLogin", "false");
		
		return "home";
	}
	
	@RequestMapping(value = "/home", method = RequestMethod.GET)
	public String home2(Locale locale, Model model, HttpServletRequest httpServletRequest) {
	
		return "redirect:/";
	}
	
	
	
	
	
	
	
}

src/main/java/com/elec5619/bitpal/web/LoginController.java
package com.elec5619.bitpal.web;

import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.elec5619.bitpal.domain.User;
import com.elec5619.bitpal.service.UserManager;

@Controller
public class LoginController {
	
private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	@Resource(name="userManager")
	UserManager userManager;
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String login(HttpServletRequest httpServletRequest, HttpServletResponse response, Model model) {
		
		
		// If already logged in. Log out!
		//if (session.getAttribute("authenticated") != null) {
		//	return "redirect:dashboard";
		//}
		
		HttpSession session = httpServletRequest.getSession();
		
		
		
		if(!(session.getAttribute("Authentication") == null))
		{
			if(session.getAttribute("Authentication").equals("false"))
			{
				if(!(session.getAttribute("AttemptedLogin") == null))
				{
					if(session.getAttribute("AttemptedLogin").equals("true"))
					{
						model.addAttribute("authenticationMessage", "Authentication failed");
					
					}
				
						model.addAttribute("authenticationMessage", "");
				}
				
				model.addAttribute("authenticationMessage", "");
			
			}
			
			else if (session.getAttribute("Authentication").equals("true"))
			{
//				model.addAttribute("authenticationMessage", "You are already logged in!");
				return "home";
			}
			
			else
				model.addAttribute("authenticationMessage", "");
		}
		
				
		
		else
		{
			model.addAttribute("authenticationMessage", "");
			
		}
		
		return "login";
	}
	
	/**
	 * Very basic verification of login username and password
	 * @throws InvalidKeySpecException 
	 * @throws NoSuchAlgorithmException 
	 */
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String verifyLogin(HttpServletRequest httpServletRequest, Model model) throws NoSuchAlgorithmException, InvalidKeySpecException
	{
		String username = httpServletRequest.getParameter("username");
		String password = httpServletRequest.getParameter("password");
		User user = userManager.login(username, password);
		HttpSession session = httpServletRequest.getSession();
		
		if (user  != null)
		{	
			session.setAttribute("AuthenticatedUser", user);
			session.setAttribute("Authentication", "true");
			return "redirect:/authorize.html";

		}
		
		else
		{
			session.removeAttribute("AttemptedLogin");
			session.setAttribute("AttemptedLogin", "true");
			session.setAttribute("Authentication", "false");
			model.addAttribute("authenticationMessage", "Authentication failed");
			return "login";
		}
		
		
		//lastUpdated
	}
	
	@RequestMapping(value = "/logout", method = RequestMethod.POST)
	public String logout(HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		session.invalidate();
		return "redirect:/login";
	}
	

}

src/main/webapp/WEB-INF/views/avatarcustomization.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<head>
	<title>Avatar Customization</title>
</head>
<body>
    <div class="jumbotron">
        <h1 class="text-center">Avatar Customization</h1>
        <p class="text-center">Here you can customize the items on you Avatar!</p>
   	</div>

<!-- <form name="populate" action="avatarcustomization.htm" method="post"> -->
<!-- 	<input type="submit" value="Populate database"> -->
<!-- </form> -->
<h3><button class="btn btn-lg btn-success btn-block">Equipped Items</button></h3>
	<c:if test="${items.size() == 0}">
		<p class="text-center bg-danger">No Items found in database</p>
	</c:if>
<table class="table table-hover table-condensed bg-success">
  <thead>
  <tr>
  	<th>Name</th>
    <th>Price</th>
    <th>Type</th>		
    <th>Unequip?</th>
  </tr>
  </thead>
  <tbody>
	<c:forEach items="${items}" var="item">
		<tr>
		<c:if test="${item.equipped == true }">
		<td><c:out value="${item.name}"/></td>
		<td><c:out value="${item.price}"/></td>
		<td><c:out value="${item.type}"/></td>
		<td>
			<form name="toggle" action="avatarcustomization.htm" method="post">
				<input type="hidden" Value="${item.id}" name="id">
				<input type="submit" Value="Unequip" name="current">
			</form>
		</td>
		</c:if>
		</tr>
	</c:forEach>
	</tbody>
</table>
<br />
<br />
<h3><button class="btn btn-lg btn-info btn-block">Inventory</button></h3>
<table class="table table-hover table-condensed bg-info">
<thead>
  <tr>
  	<th>Name</th>
    <th>Price</th>
    <th>Type</th>		
    <th>Equip?</th>
  </tr>
</thead>
<tbody>
	<c:forEach items="${items}" var="item">
		<tr>
		<c:if test="${item.equipped == false }">
		<td><c:out value="${item.name}"/></td>
		<td><c:out value="${item.price}"/></td>
		<td><c:out value="${item.type}"/></td>
		<td>
			<form name="toggle" action="avatarcustomization.htm" method="post">
				<input type="hidden" Value="${item.id}" name="id">
				<input type="submit" Value="Equip" name="current">
			</form>
		</td>
		</c:if>
		</tr>
	</c:forEach>
</tbody>
</table>
</body>
</html>

src/main/webapp/WEB-INF/views/battle.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<head>
<title>Battle</title>
</head>
<body>
	<h1 align="center"><c:out value="${self.username} vs. ${friend.username}"/> </h1>
	<c:if test="${friendScore > userScore}">
		<div align="center"> <img src="<c:url value= "/resources/Images/lost.gif"/>" id="fight"/></div>
	</c:if>
	
	<c:if test="${friendScore < userScore}">
	<div align="center"> <img src="<c:url value= "/resources/Images/won.gif"/>" id="fight"/></div>
	</c:if>
	
	<c:if test="${friendScore == userScore}">
		<div align="center"> <img src="<c:url value= "/resources/Images/draw.gif"/>" id="fight"/></div>
	</c:if>


	</body>
</html>

src/main/webapp/WEB-INF/views/confirmed.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<script>
function msg(product)
{
alert(product);

}
</script>


<div class="container-fluid">
    <div class="jumbotron">
        <h1>Purchase Summary </h1>
        <p> ${msg} </p>
     </div>
<p></p>

</div>

 
 <div class="alert alert-info alert-sm" style="text-align:center">
 
 <a href="<c:url value="/shop" />"> Return to store </a> </div>

</html>

src/main/webapp/WEB-INF/views/dashboard.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
<head>
	<title>Home</title>
</head>
<body>
<h1>
	Hello World! Dashboard
</h1>

<P>  The time on the server is ${serverTime}. </P>
<a href="avatarcustomization.htm">Avatar Customization</a>

</body>
</html>

src/main/webapp/WEB-INF/views/friends.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<head>
<!-- <script type=text/javascript src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js"></script>-->
<!-- <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>-->
<script type="text/javascript">
/*$(document).ready(function () {
	var $rows = $('#users tr');
	$('#searchUsers').keyup(function() {
	    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();

	    $rows.show().filter(function() {
	        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
	        return !~text.indexOf(val);
	    }).hide();
	});
}); */
</script>
<title>Friends</title>

</head>
<body>
  <div class="jumbotron">
        <h1 class="text-center">Friends</h1>
        <p class="text-center">Add or remove friends and view their profiles!</p>
   	</div>
   	<h3>Friends</h3>
	<!--  Table search of friends -->
	<c:if test="${friends.size() == 0}">	
		<p> You have no friends. Add some from below! </p>
	</c:if>

	<c:if test="${friends.size() != 0}">
		<!--<div style='text-align: center'><input type="text" id="search" placeholder="Type to search" style="margin: 0px auto; width: 90%; font-size: 14pt;"></div>-->
		<table class="table table-hover table-condensed bg-success">
     	<tr align="center">
    		<th width = 20%>Username</th>
    		<th width = 20%>Experience</th>  
	    	<th width = 20%>Delete?</th>
	    	<th width = 20%>View Profile?</th>    
	  	</tr>  	
  	 
    	 <c:forEach items="${friends}" var="friend">
	     	<tr>
		     	<td><c:out value="${friend.username}"/></td>
				<td><c:out value="${friend.experience}"/></td>     	
		     	<td>
					<form name="addFriend" action="friends.htm" method="post">
						<input type="hidden" Value="${friend.id}" name="id">
						<input type="submit" Value="Delete Friend" name="current">
					</form>
				</td>
				<td>
					<form name="viewFriend" action="friendsProfile" method="post">
						<input type="hidden" Value="${friend.id}" name="id">
						<input type="hidden" Value="${self.username}" name="self">
						<input type="submit" Value="View Profile" name="current">
					</form>
				</td>
	     	</tr>
     	</c:forEach>
     	</table>
     	</c:if>
     
  	
 
     
	
		
	
		<!-- Table of all users -->
	<h3>Add new friends</h3>
		<!--  Table search of friends -->
	<c:if test="${users.size() == 0}">
		<p> No users are registered </p>
	</c:if>
	<c:if test="${users.size() != 0}">
		<!--<div style='text-align: center'><input type="text" id="search" placeholder="Type to search" style="margin: 0px auto; width: 90%; font-size: 14pt;"></div>-->
		<table class="table table-hover table-condensed bg-success">
	     <tr align="center">
	    	<th width = 20%>Username</th>
	    	<th width = 20%>Experience</th>  
	    	<th width = 20%>Add?</th>    
	  	</tr>
	     <c:forEach items="${users}" var="user">
		     <tr>
		     <c:if test="${user.friend == false && user.username != self.username}">
		     	<td><c:out value="${user.username}"/></td>
				<td><c:out value="${user.experience}"/></td>
		     	<td>
					<form name="addFriend" action="friends.htm" method="post">
						<input type="hidden" Value="${user.id}" name="id">
						<input type="submit" Value="Add Friend" name="current">
					</form>
				</td>
			</c:if>
     		</tr>
     	</c:forEach>
     	</table>
     </c:if>
     
	
</body>

</html>



<!-- OLD CODE -->
	
	<!-- <div style='text-align: center'><input type="text" id="search" placeholder="Type to search" align="middle" style="margin: 0px auto; width: 90%; font-size: 14pt;"></div>
	<table id="friends" position='fixed' bottom=0 align="center" style="margin: 0px auto; width: 90%;  left-padding: 100px; border: 1px solid black; font-family: Arial; border-collapse: collapse; text-align: center;">
		<tr>
			<th style="text-align: center;">Friends</th>
			<th style="text-align: center;">Ranking</th>
		</tr>
		<tr>
			<td style="background-color: #BABABA;"><a href='/bitpal/friendsProfile'>YourWorstNightmare</a></td>
			<td style="background-color: #BABABA;">12</td>
		</tr>
		<tr>
			<td>FitnessFreak</td>
			<td>2</td>
		</tr>
		<tr>
			<td style="background-color: #BABABA;">GymBuff</td>
			<td style="background-color: #BABABA;">7</td>
		</tr>
		<tr>
			<td>Bob</td>
			<td>17</td>
		</tr>
		<tr>
			<td style="background-color: #BABABA;">WalkMaster</td>
			<td style="background-color: #BABABA;">53</td>
		</tr>
	</table> -->
	